src/Entity/Projet.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use App\Repository\ProjetRepository;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File;
use Symfony\Component\HttpFoundation\File\File as FileFile;
use Symfony\Component\HttpFoundation\File\UploadedFile;


/**
 * @ORM\Entity(repositoryClass=ProjetRepository::class)
 * @UniqueEntity("nom")
 * @Vich\Uploadable()
 */
class Projet
{
    const STATUT = [
        true => 'Finit',
        false => 'A la recherche d\' un artisan '
    ];
    const TRAVAUX = [
        1 => 'Electricien',
        2 => 'Peintre',
        3 => 'Plombier',
        4 => 'Renovation sdb',
        5 => 'Renovation cuisine',
        6 => 'Poseur de sol',
        7 => 'Poseur papier peint',
        8 => 'Demolition mur',
        9 => 'Renovation mur',
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=40)
     */
    private $nom;


    /**
     * @ORM\Column(type="float")
     * @Assert\Range(min=100, max=500000)
     */
    private $budget;



    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $dateDeDebut;

    public function __construct()
    {
        $this->dateDeDebut = new \DateTime();
    }

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     * 
     */
    private $filename;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     * 
     */
    private $imageFile;


    /**
     * @ORM\Column(type="boolean")
     */
    private $statut;



    /**
     * @ORM\Column(type="integer")
     */
    private $travaux;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="projets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;






    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getSlug(): string
    {

        return (new Slugify())->slugify($this->nom);
    }

    public function getBudget(): ?float
    {
        return $this->budget;
    }

    public function setBudget(float $budget): self
    {
        $this->budget = $budget;

        return $this;
    }



    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDeDebut(): ?\DateTimeInterface
    {
        return $this->dateDeDebut;
    }

    public function setDateDeDebut(\DateTimeInterface $dateDeDebut): self
    {
        $this->dateDeDebut = $dateDeDebut;

        return $this;
    }


    public function getStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(bool $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getStatutType(): string
    {
        return self::STATUT[$this->statut];
    }



    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get the value of filename
     *
     * @return  string|null
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Set the value of filename
     *
     * @param  string|null  $filename
     *
     * @return  self
     */
    public function setFilename($filename)
    {
        $this->filename = $filename;

        return $this;
    }

    /**
     * Get the value of imageFile
     *
     * @return  File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set the value of imageFile
     *
     * @param  File  $imageFile
     *
     * @return  self
     */
    public function setImageFile(FileFile $imageFile)
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->dateDeDebut = new \DateTime('now');
        }

        return $this;
    }

    /**
     * Get the value of travaux
     */ 
    public function getTravaux()
    {
        return $this->travaux;
    }

    /**
     * Set the value of travaux
     *
     * @return  self
     */ 
    public function setTravaux($travaux)
    {
        $this->travaux = $travaux;

        return $this;
    }

    public function getTravauxType(): string
    {

        return self::TRAVAUX[$this->travaux];
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Repository\ProjetRepository;
use App\Form\ContactType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Notification\ContactNotification;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FrontController extends AbstractController
{



    #[Route("/", name: 'index')]
    public function index(ProjetRepository $repository): Response
    {
        $projetss = $repository->findLatest();

        return $this->render("front/index.html.twig", ['projetss' => $projetss]);
    }




    #[Route("/contact", name: 'contact')]
    public function contact(Request $request, ContactNotification $notification): Response

    {

        $contact = new Contact();
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // $notification->notify($contact);
            $notification->notify($contact);
            // $this->addFlash('success', 'votre email a bien été envoyé');
            $this->addFlash('success', 'votre email a bien été envoyé vous aurez une réponse sous 48h');
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($contact);
            $entityManager->flush();

            return $this->redirectToRoute('contact');
        }


        return $this->render("front/contact.html.twig",   [
            'contact' => $contact,
            'form' => $form->createView()
        ]);
    }





    #[Route("/login", name: 'login')]
    public function login(): Response
    {
        return $this->render("front/login.html.twig");
    }

    #[Route("/inscription", name: 'inscription')]
    public function inscription(): Response
    {
        return $this->render("front/inscription.html.twig");
    }
}

templates/front/about.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary py-5">
        <div class="container py-5">
            <div class="row align-items-center py-4">
                <div class="col-md-6 text-center text-md-left">
                    <h1 class="mb-4 mb-md-0 text-primary text-uppercase">About Us</h1>
                </div>
                <div class="col-md-6 text-center text-md-right">
                    <div class="d-inline-flex align-items-center">
                        <a class="btn btn-outline-primary" href="">Home</a>
                        <i class="fas fa-angle-double-right text-primary mx-2"></i>
                        <a class="btn btn-outline-primary disabled" href="">About Us</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header Start -->


    <!-- About Start -->
    <div class="container-fluid bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <div class="d-flex flex-column align-items-center justify-content-center bg-primary h-100 py-5 px-3">
                        <i class="flaticon-brickwall display-1 font-weight-normal text-secondary mb-3"></i>
                        <h4 class="display-3 mb-3">25+</h4>
                        <h1 class="m-0">Years Experience</h1>
                    </div>
                </div>
                <div class="col-lg-7 m-0 my-lg-5 pt-5 pb-5 pb-lg-2 pl-lg-5">
                    <h6 class="text-primary font-weight-normal text-uppercase mb-3">Learn About Us</h6>
                    <h1 class="mb-4 section-title">We Are The Best Interior Designing Firm In Your City</h1>
                    <p>Invidunt lorem justo sanctus clita. Erat lorem labore ea, justo dolor lorem ipsum ut sed eos, ipsum et dolor kasd sit ea justo. Erat justo sed sed diam. Ea et erat ut sed diam sea ipsum est dolor</p>
                    <div class="row py-2">
                        <div class="col-sm-6">
                            <div class="d-flex align-items-center mb-4">
                                <h1 class="flaticon-house font-weight-normal text-primary m-0 mr-3"></h1>
                                <h5 class="text-truncate m-0">Project Planning</h5>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="d-flex align-items-center mb-4">
                                <h1 class="flaticon-stairs font-weight-normal text-primary m-0 mr-3"></h1>
                                <h5 class="text-truncate m-0">Exterior & Interior</h5>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="d-flex align-items-center mb-4">
                                <h1 class="flaticon-office font-weight-normal text-primary m-0 mr-3"></h1>
                                <h5 class="text-truncate m-0">Commercial Design</h5>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="d-flex align-items-center mb-4">
                                <h1 class="flaticon-living-room font-weight-normal text-primary m-0 mr-3"></h1>
                                <h5 class="text-truncate m-0">Residential Design</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->


    <!-- Features Start -->
    <div class="container-fluid bg-white">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 mt-5 py-5 pr-lg-5">
                    <h6 class="text-primary font-weight-normal text-uppercase mb-3">Why Choose Us?</h6>
                    <h1 class="mb-4 section-title">25+ Years Experience In The Interior Design Industry</h1>
                    <p class="mb-4">Dolores lorem lorem ipsum sit et ipsum. Sadip sea amet diam dolore sed et. Sit rebum labore sit sit ut vero no sit. Et elitr stet dolor sed sit et sed ipsum et kasd ut. Erat duo eos et erat sed diam duo</p>
                    <ul class="list-inline">
                        <li><h5><i class="far fa-check-square text-primary mr-3"></i>25+ Years Experience</h5></li>
                        <li><h5><i class="far fa-check-square text-primary mr-3"></i>Best Interior Design</h5></li>
                        <li><h5><i class="far fa-check-square text-primary mr-3"></i>Customer Satisfaction</h5></li>
                    </ul>
                    <a href="" class="btn btn-primary mt-3 py-2 px-4">View More</a>
                </div>
                <div class="col-lg-5">
                    <div class="d-flex flex-column align-items-center justify-content-center h-100 overflow-hidden">
                        <img class="h-100" src="img/feature.jpg" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Features End -->


    <!-- Team Start -->
    <div class="container-fluid bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-6">
                    <div class="py-5 px-4 h-100 bg-primary d-flex flex-column align-items-center justify-content-center">
                        <h6 class="text-white font-weight-normal text-uppercase mb-3">Our Team</h6>
                        <h1 class="mb-0 text-center">Meet Our Team Members</h1>
                    </div>
                </div>
                <div class="col-md-8 col-sm-6 p-0 py-sm-5">
                    <div class="owl-carousel team-carousel position-relative p-0 py-sm-5">
                        <div class="team d-flex flex-column text-center mx-3">
                            <div class="position-relative">
                                <img class="img-fluid w-100" src="img/team-1.jpg" alt="">
                                <div class="team-social d-flex align-items-center justify-content-center w-100 h-100 position-absolute">
                                    <a class="btn btn-outline-primary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-outline-primary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-outline-primary text-center px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="d-flex flex-column bg-secondary text-center py-3">
                                <h5 class="text-white">Name Goes Here</h5>
                                <p class="m-0">Designation</p>
                            </div>
                        </div>
                        <div class="team d-flex flex-column text-center mx-3">
                            <div class="position-relative">
                                <img class="img-fluid w-100" src="img/team-2.jpg" alt="">
                                <div class="team-social d-flex align-items-center justify-content-center w-100 h-100 position-absolute">
                                    <a class="btn btn-outline-primary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-outline-primary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-outline-primary text-center px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="d-flex flex-column bg-secondary text-center py-3">
                                <h5 class="text-white">Name Goes Here</h5>
                                <p class="m-0">Designation</p>
                            </div>
                        </div>
                        <div class="team d-flex flex-column text-center mx-3">
                            <div class="position-relative">
                                <img class="img-fluid w-100" src="img/team-3.jpg" alt="">
                                <div class="team-social d-flex align-items-center justify-content-center w-100 h-100 position-absolute">
                                    <a class="btn btn-outline-primary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-outline-primary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-outline-primary text-center px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="d-flex flex-column bg-secondary text-center py-3">
                                <h5 class="text-white">Name Goes Here</h5>
                                <p class="m-0">Designation</p>
                            </div>
                        </div>
                        <div class="team d-flex flex-column text-center mx-3">
                            <div class="position-relative">
                                <img class="img-fluid w-100" src="img/team-4.jpg" alt="">
                                <div class="team-social d-flex align-items-center justify-content-center w-100 h-100 position-absolute">
                                    <a class="btn btn-outline-primary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-outline-primary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-outline-primary text-center px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="d-flex flex-column bg-secondary text-center py-3">
                                <h5 class="text-white">Name Goes Here</h5>
                                <p class="m-0">Designation</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Team End -->


    {% endblock %}

templates/front/contact.html.twig
{% extends "base.html.twig" %}

{% block body %}


    {# <!-- Page Header Start -->
    <div class="container-fluid bg-secondary py-5">
        <div class="container py-5">
            <div class="row align-items-center py-4">
                <div class="col-md-6 text-center text-md-left">
                    <h1 class="mb-4 mb-md-0 text-primary text-uppercase">Contact Us</h1>
                </div>
                <div class="col-md-6 text-center text-md-right">
                    <div class="d-inline-flex align-items-center">
                        <a class="btn btn-outline-primary" href="">Home</a>
                        <i class="fas fa-angle-double-right text-primary mx-2"></i>
                        <a class="btn btn-outline-primary disabled" href="">Contact Us</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header Start --> #}


    <!-- Contact Start -->
    <div class="container-fluid bg-white">
        <div class="container">
        {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
            </div>
            {% endfor %}
            <div class="row">
                <div class="col-lg-4">
                    <div class="d-flex flex-column justify-content-center bg-primary h-95 p-5 mt-5">
                        <div class="d-inline-flex border border-secondary p-4 mb-4">
                            <h1 class="flaticon-office font-weight-normal text-secondary m-0 mr-3"></h1>
                            <div class="d-flex flex-column">
                                <h4>Notre bureau</h4>
                                <p class="m-0 text-white">Brussel, Belgium</p>
                            </div>
                        </div>
                        <div class="d-inline-flex border border-secondary p-4 mb-4">
                            <h1 class="flaticon-email font-weight-normal text-secondary m-0 mr-3"></h1>
                            <div class="d-flex flex-column">
                                <h4>Email Us</h4>
                                <p class="m-0 text-white">info@ideco.be</p>
                            </div>
                        </div>
                        <div class="d-inline-flex border border-secondary p-4">
                            <h1 class="flaticon-telephone font-weight-normal text-secondary m-0 mr-3"></h1>
                            <div class="d-flex flex-column">
                                <h4>Call Us</h4>
                                <p class="m-0 text-white">+32 (0)2 345 678</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7 mb-7 my-lg-5 py-5 pl-lg-5 " >
                          {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
                    <h1 style="margin-bottom:50px">Contact</h1>
                    <div class="contact-form" >
                             {{ form_start(form)}}
    <div class='row'>
    <div class="col">{{ form_row(form.nom)}}</div>
    </div>
    <div class='row'>
    <div class="col">{{ form_row(form.email)}}</div>
    </div>
<div class='row'>
    <div class="col">{{ form_row(form.message)}}</div>
    </div>
    <div class="form-group">
        <button class="btn btn-primary">Envoyer</button>
    </div>
     {{ form_end(form)}}
                        {# <form name="sentMessage" id="contactForm" novalidate="novalidate">
                            <div class="control-group">
                                <input type="text" class="form-control p-4" id="nom" placeholder="Your Name" required="required" data-validation-required-message="Please enter your name" />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input type="email" class="form-control p-4" id="email" placeholder="Your Email" required="required" data-validation-required-message="Please enter your email" />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <textarea class="form-control p-4" rows="6" id="message" placeholder="Message" required="required" data-validation-required-message="Please enter your message"></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div>
                                <button class="btn btn-primary py-3 px-5" type="submit" id="sendMessageButton">Send Message</button>
                            </div>
                        </form> #}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


       {% endblock %}

templates/front/projet.html.twig
{% extends "base.html.twig" %}

{% block title "tous nos biens"%}

{% block body %}




<div class='container'>
<div class='jumbotron '>
<div class="row justify-content-center">
                <div class="col-lg-10 col-md-8 col text-center mb-4">
                  <h1 class="mb-4">Tous les projets de nos clients</h1>
                    <h6 class="text-primary font-weight-normal text-uppercase mb-3">Voir par filtres</h6>
                
<div class='container '>
{{ form_start(form)}}

    <div class="form-row align-items-end">
        <div class="col">
        {{ form_row (form.budget)}}
        </div>
        <div class="col">
        {{ form_row (form.travaux)}}
        </div>

<div class="col ">
<div class="form-group">
<button class="btn btn-primary">Recherche</button>
</div>
</div>
</div>
{{ form_end(form)}}
</div>
</div>
                  
                </div>
            </div>

   <div class="row flex mb-3" >
        {% for proj in projetss %}
            <div class="col-3 mb-3">
                <div class="card">
                       {% if proj.filename %}
                      <img src="{{ vich_uploader_asset(proj, 'imageFile')  }}" alt="card-img-top" style="width: 100%; height:170px;">
                       {% else %}
                        <img src="{{ 'assets/img/Ixina.jpg'  }}" alt="card-img-top" style="width: 100%; height:170px;">
                       {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{{ path('front.show', {id: proj.id, slug: proj.slug}) }}">{{ proj.nom }}</a>
                            </h5>
                        <p class="card-text">{{ proj.travauxType }}</p>    
                        <p class="card-text">{{ proj.description }}</p>
                           {# <p class="card-text">{{ proj.user.nom }}</p> #}
                       
                        <div class='text-primary'>{{proj.budget | number_format (0,'',' ' )}} euros</div>
                            </div>
                            </div>
                            </div>
        {% endfor %}

        <div class="pagination mb-2 ">
                {{ knp_pagination_render(projetss) }}
            </div>
       {% endblock %}

templates/front/show.html.twig
{% extends 'base.html.twig' %}
{% block title projet.nom %}
{% block body %}
<div class="jumbotron">
    <div class="container">

        {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
            </div>
            {% endfor %}
     <div class="row">
        <div class="col-md-7">
         <div class="col-md-16">
                     <h2>Travaux: {{ projet.travauxType}}
                     </div>
                      <div class="text-primary" style="font-size: 2rem; font-weight: bold;">Budget: {{ projet.budget}} euros</div>
                      <img src=" /assets/img/{{projet.fileName}} " alt="card-img-top" style="width: 70%; height:auto;">
            </div>
            <div class="col-md-5">
<h1>{{ projet.nom}}</h1>
     <p class="text-primary">Si vous êtes un artisan et que vous êtes intéressés par le projet merci de remplir
     le formulaire ci dessous qui sera soumis au propriétaire</p>
     <div id="artisanForm" class="mt-4">
     {{ form_start(form)}}
    <div class='row'>
    <div class="col">{{ form_row(form.nom)}}</div>
    <div class="col">{{ form_row(form.metier)}}</div>
    </div>
    <div class='row'>
    <div class="col">{{ form_row(form.email)}}</div>
    </div>
<div class='row'>
    <div class="col">{{ form_row(form.description)}}</div>
    </div>
    <div class="form-group">
        <button class="btn btn-primary">Envoyer</button>
    </div>
     {{ form_end(form)}}
     </div>

    </div>

</div>
</div>
</div>
<div class='container mt-4'>

        <div class="row">
            <div class="col-md-8">
                <h3 style="margin-bottom: 20px">Caractéristiques</h3>
                   <p>{{ projet.description | nl2br }}</p>
                <p>Budget: {{ projet.budget}} euros</p>
                <p> Statut: {{ projet.statutType}}</p>
 </div>
    </div>


</div>




{% endblock %}